version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo ”this is a build job”
  test:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run: echo “this is a test job”

workflows:
  build-and-test:
    jobs:
      - build
      - test
        requires:
          - build

