version: 2.1

jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo ”say this first”
  two:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run: echo “say this second”

workflows:
  one-and-two:
    jobs:
      - one
      - two
  one-then-two:
    jobs:
      - one
      - two:
          requires:
            - one
